# Generated by Django 3.2.25 on 2024-04-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='组名称')),
            ],
            options={
                'verbose_name': '任务组列表',
                'db_table': 'task_group',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('task_time_start', models.TimeField(verbose_name='任务开始时间')),
                ('task_time_end', models.TimeField(verbose_name='任务截止时间')),
                ('task_title', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_desc', models.TextField(blank=True, null=True, verbose_name='任务详情')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TasksRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '任务完成列表',
                'verbose_name_plural': '任务完成列表',
                'db_table': 'tasks_record',
            },
        ),
    ]
