# Generated by Django 3.2.25 on 2024-04-21 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksrecord',
            name='audit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_by', to='user_app.user', verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='tasksrecord',
            name='completed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_by', to='user_app.user', verbose_name='完成人'),
        ),
        migrations.AddField(
            model_name='tasksrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.tasks', verbose_name='任务'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.user', verbose_name='创建人'),
        ),
    ]
