# Generated by Django 3.2.25 on 2024-04-22 14:27

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_auto_20240422_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='task_app.tasks', verbose_name='任务'),
        ),
    ]
