# Generated by Django 3.2.25 on 2024-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_tasks_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('action', models.CharField(max_length=100, verbose_name='行为')),
                ('content', models.TextField(verbose_name='操作内容')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
                'db_table': 'tasks_log',
            },
        ),
    ]
