# Generated by Django 3.2.25 on 2024-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_tasks_task_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='create time', verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='update time', verbose_name='update time')),
                ('action', models.CharField(max_length=100, verbose_name='action')),
                ('content', models.TextField(verbose_name='operation')),
            ],
            options={
                'verbose_name': 'task_log',
                'verbose_name_plural': 'task_log',
                'db_table': 'tasks_log',
            },
        ),
    ]
