# Generated by Django 3.2.25 on 2024-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_taskslog_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskslog',
            name='task_desc',
            field=models.TextField(default='', verbose_name='任务详情'),
            preserve_default=False,
        ),
    ]
