# Generated by Django 3.2.25 on 2024-05-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_tasksrecord_bz'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksrecord',
            name='completed_time',
            field=models.DateTimeField(default='2024-05-15 00:00:00', verbose_name='完成时间'),
            preserve_default=False,
        ),
    ]
