# Generated by Django 3.2.25 on 2024-05-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0015_tasksrecord_completed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='day',
            field=models.IntegerField(default=1, verbose_name='间隔天数'),
        ),
    ]
